// import React from 'react';
// import { Dialog, DialogContent } from '@/components/ui/dialog';

// const BMIPopup = ({
//   isOpen,
//   onClose,
//   bmiCategory,
//   gender
// }: {
//   isOpen: boolean;
//   onClose: () => void;
//   bmiCategory: string;
//   gender: string;
// }) => {
//   const disclaimer = `*Note: Disclaimer The BMI Classification App utilizes a neural network model to estimate your Body Mass Index (BMI) and classify it based on the inputted height, weight, and gender data. While the neural network has been trained on a diverse dataset to provide accurate predictions, it is important to note that the results are generated by an artificial intelligence system and may not account for all individual health factors. The BMI classifications provided by this app are for informational purposes only and should not be considered a substitute for professional medical advice, diagnosis, or treatment. The results are based on general statistical trends and may not accurately reflect your personal health status, as factors such as muscle mass, bone density, and fat distribution are not considered in the BMI calculation. Neural networks, like any predictive models, have limitations and can produce incorrect or misleading results under certain conditions. The creators of the BMI Classification App are not responsible for any decisions made based on the information provided by this app. By using this app, you agree to assume full responsibility for any actions taken based on its results and understand that the information provided may not be applicable to your specific health conditions. If you have any concerns about your health or BMI classification, it is strongly recommended to consult with a qualified healthcare provider who can provide personalized advice and guidance based on a comprehensive evaluation of your health.`;

//   const getImagePath = () => {
//     const baseCategory = bmiCategory.toLowerCase().replace(' ', '-');
//     return `/bmi-${gender.toLowerCase()}-${baseCategory}.svg`;
//   };

//   return (
//     <Dialog open={isOpen} onOpenChange={onClose}>
//       <DialogContent className="max-w-4xl p-0 overflow-hidden bg-white rounded-lg">
//         <div className="relative">
//           {/* Result Section */}
//           <div className="p-6 animate-slideDown">
//             <h2 className="text-xl font-bold text-center text-[#1A2A44] mb-4">
//               Based on the data you entered, you fall into the {bmiCategory} category.
//             </h2>
//             <p className="text-center text-[#1A2A44] mb-6">
//               Maintain a healthy lifestyle and consult a nutritionist if necessary!
//             </p>

//             {/* BMI Meter Image */}
//             <div className="relative w-full h-[400px] mb-6 animate-fadeIn">
//               <img
//                 src={getImagePath()}
//                 alt={`BMI Meter - ${gender} ${bmiCategory}`}
//                 className="w-full h-full object-contain"
//               />
//             </div>

//             {/* Disclaimer */}
//             <div className="text-xs text-gray-600 mt-4 animate-fadeIn delay-300">
//               {disclaimer}
//             </div>
//           </div>
//         </div>
//       </DialogContent>
//     </Dialog>
//   );
// };

// export default BMIPopup;
